#!/usr/bin/env python3
"""
Django's command-line utility for administrative tasks.
This script is generated by the Django project scaffolding.  It simply
sets the appropriate environment variable so that Django knows where to
find your settings and executes the command-line utility to handle
database migrations, server start and other commands.

We vendor the manage.py rather than relying on the `django-admin startproject`
command because the container environment cannot access PyPI.  This file
assumes that Django is available on the Python path.  If you install
Django into a virtual environment you should run management commands via
``python manage.py <command>`` from the project root.
"""
import os
import sys


def main() -> None:
    """Run administrative tasks."""
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'anumc_website.settings')
    try:
        from django.core.management import execute_from_command_line  # type: ignore
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and available "
            "on your PYTHONPATH environment variable? Did you forget to "
            "activate a virtual environment?"
        ) from exc
    execute_from_command_line(sys.argv)


if __name__ == '__main__':
    main()